# Generated by Django 5.0.6 on 2024-07-15 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('release_date', models.DateField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='почта')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=250, null=True, verbose_name='Улица')),
                ('house_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('debt', models.FloatField(blank=True, default=0, null=True, verbose_name='Задолженность')),
                ('create_time', models.DateTimeField(verbose_name='Дата создания')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_network.link', verbose_name='Поставщик')),
                ('product', models.ManyToManyField(default=None, to='sales_network.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Звено',
                'verbose_name_plural': 'Звенья',
            },
        ),
    ]
