# Generated by Django 5.0.6 on 2024-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
